name: Deploy to GCP VM

on:
  push:
    branches:
      - main  # change to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd /home/kelvinmbugua/ic-robots            # ← your app directory on the VM
            git pull origin main
            npm install --production
            pm2 startOrRestart ecosystem.config.js --only ic-scalping-bot --update-env
            pm2 save
